print("Bem vindo ao seu primeiro código!")
print(" ")
nome = input("Digite o seu nome: ")
peso = float(input("Digite o seu peso: "))
idade = int(input("Digite a sua idade: "))
altura = float(input("Digite a sua altura: "))
imc = (peso/(altura*altura))
print("--------------------")
print(nome)
print(peso)
print(idade)
print(altura)
print("Seu IMC é: ", imc)
print("--------------------")
print("where is my code in git?")